version: 2
jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: 4ad7081c76a2eae72cfec64b0a57a43bbf2bca5525e14d1a36a673eb980a88f1
    docker:
      # specify the version you desire here
      - image: circleci/node:10.11
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Setup Code Climate test-reporter
          command: |
            # download test reporter as a static binary
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
        
      - run:
          name: Update Code Climate that we are running the tests
          command: |
            ./cc-test-reporter before-build

      # run tests!
      - run:
          name: Run tests
          command: yarn test:ci
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
            CI: true

      - store_test_results:
          path: test-results

      - store_test_results:
          path: reports/junit

      - run:
          name: Upload test coverage to CodeClimate
          command: |
            ./cc-test-reporter after-build --exit-code $?

          

