version: 2
jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: 4ad7081c76a2eae72cfec64b0a57a43bbf2bca5525e14d1a36a673eb980a88f1
    docker:
      # specify the version you desire here
      - image: circleci/node:10.11
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: yarn test

      - store_artifacts:
          path: coverage
          prefix: coverage

      - run:
          name: Update Code Climate
          command: |
            ./cc-test-reporter before-build
            ./cc-test-reporter after-build --coverage-input-type clover --exit-code $?

